name: camera_mobile_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  cupertino_icons: ^1.0.6
  extensions_kit: ^1.1.0
  flutter:
    sdk: flutter
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  printing: ^5.13.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
